-- MySQL Workbench Synchronization
-- Generated: 2020-02-25 12:25
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: katie

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `activity`.`posts` (
  `postid` INT(11) NOT NULL AUTO_INCREMENT,
  `userID_PostBy` INT(11) NULL DEFAULT NULL,
  `userID_LastPost` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(50) NULL DEFAULT NULL,
  `content` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`postid`),
  INDEX `userID_PostBy_idx` (`userID_PostBy` ASC) VISIBLE,
  CONSTRAINT `userID_PostBy`
    FOREIGN KEY (`userID_PostBy`)
    REFERENCES `activity`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
